Fix/demographics-call-rescue-404
Arux-Software/Bright pull request #26
Opened 2022-04-27 22:08 UTC by brgeen

[Sentry Error](https://sentry.io/organizations/arux-software/issues/3191865299/?project=5177588&query=is%3Aunresolved)

This adds a `begin/rescue` block to the demographics call. If the response is a 404 we rescue the error and return an empty  hash instead of the program crashing. 

**Before**: 
```ruby
campus.get_demographic_information('26C6BF04-488D-40AD-8544-13E0DB7A4C08')
Bright::ResponseError (Failed with 404)
```
program crashes, no further code is executed 

**After**: 
```ruby
campus.get_demographic_information('26C6BF04-488D-40AD-8544-13E0DB7A4C08')
Failed with 404
=> {}
```
an empty hash is returned and it gets handled with the [guard clause here](https://github.com/Arux-Software/Bright/blob/3e747741edad1c586cbdb5ec2b6d9b46d8e2458e/lib/bright/sis_apis/infinite_campus.rb#L318)

If we hit further issues we can try filtering out users in the `get_students` call. Something like this, but we would have to conditional render the `role(s)` key depending on the api version. 
```ruby
students = students_hash.compact.collect do |st_hsh|
  next unless st_hsh['roles'].flat_map(&:values).include?('student')
  Student.new(convert_to_user_data(st_hsh))
end
```

I also tried updating InfiniteCampus#map_search_params to include `when 'roles'` in the case statement, but that broke the whole process of the `get_students` call.

2022-04-27 22:19 UTC, snovotny requested changes

2022-04-27 22:19 UTC, snovotny commented on lib/bright/sis_apis/infinite_campus.rb
> +        end
I wonder if we should do something more like what we do in the case of failing to find a contact:
https://github.com/Arux-Software/Bright/blob/3e747741edad1c586cbdb5ec2b6d9b46d8e2458e/lib/bright/sis_apis/infinite_campus.rb#L323-L329

2022-04-27 22:23 UTC, brgeen commented on lib/bright/sis_apis/infinite_campus.rb
> +        end
Thats a good idea, so if we hit anything other than a 404 we want the program to stop. And if we hit a 404, we return an empty hash and carry on.

2022-04-29 18:01 UTC, snovotny approved these changes

2022-04-29 18:51 UTC, merged